/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.window.test;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Infinite World
 */
public class DashboardBck extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardBck() {
        initComponents();
       
        System.out.println(this.btnDashboard.isOpaque());
//        this.btnDashboard.setUI(new javax.swing.plaf.basic.BasicButtonUI());
//        this.btnDashboard.setBackground(new Color(0,0,0,0));
    }
    
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
//        super.paintChildren(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePane = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        btnDashboard1 = new javax.swing.JLabel();
        btnDashboard2 = new javax.swing.JLabel();
        btnDashboard3 = new javax.swing.JLabel();
        btnDashboard4 = new javax.swing.JLabel();
        btnDashboard5 = new javax.swing.JLabel();
        btnDashboard6 = new javax.swing.JLabel();
        btnDashboard7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sidePane.setkEndColor(new java.awt.Color(0, 0, 70));
        sidePane.setkGradientFocus(-20);
        sidePane.setkStartColor(new java.awt.Color(28, 181, 224));

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Simple Buy");

        btnDashboard.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/ic-window-sidemenu-petugas-home.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setIconTextGap(6);
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });

        btnDashboard1.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard1.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/ic-window-sidemenu-petugas-admin.png"))); // NOI18N
        btnDashboard1.setText("Data Karyawan");
        btnDashboard1.setIconTextGap(6);
        btnDashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard1MouseExited(evt);
            }
        });

        btnDashboard2.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard2.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/icons8_people_25px.png"))); // NOI18N
        btnDashboard2.setText("Data Pembeli");
        btnDashboard2.setIconTextGap(6);
        btnDashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard2MouseExited(evt);
            }
        });

        btnDashboard3.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard3.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/icons8_supplier_25px.png"))); // NOI18N
        btnDashboard3.setText("Data Supplier");
        btnDashboard3.setIconTextGap(6);
        btnDashboard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard3MouseExited(evt);
            }
        });

        btnDashboard4.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard4.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/icons8_product_25px.png"))); // NOI18N
        btnDashboard4.setText("Data Barang");
        btnDashboard4.setIconTextGap(6);
        btnDashboard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard4MouseExited(evt);
            }
        });

        btnDashboard5.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/ic-window-sidemenu-petugas-pembayaran.png"))); // NOI18N
        btnDashboard5.setText("Transaksi");
        btnDashboard5.setIconTextGap(6);
        btnDashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard5MouseExited(evt);
            }
        });

        btnDashboard6.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard6.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/icons8_logout_rounded_up_25px_1.png"))); // NOI18N
        btnDashboard6.setText("Logout");
        btnDashboard6.setIconTextGap(6);
        btnDashboard6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard6MouseExited(evt);
            }
        });

        btnDashboard7.setBackground(new java.awt.Color(98, 118, 234));
        btnDashboard7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDashboard7.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/icons8_graph_report_25px.png"))); // NOI18N
        btnDashboard7.setText("Laporan");
        btnDashboard7.setIconTextGap(6);
        btnDashboard7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboard7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboard7MouseExited(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/ic-window-sidemenu-petugas-akun.png"))); // NOI18N
        jLabel2.setText("Achmad Baihaqi");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/icons/icons8_paypal_60px.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout sidePaneLayout = new javax.swing.GroupLayout(sidePane);
        sidePane.setLayout(sidePaneLayout);
        sidePaneLayout.setHorizontalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePaneLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard6, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard7, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePaneLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePaneLayout.setVerticalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 929, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        this.btnDashboard.setBackground(new Color(98,118,234));
        this.btnDashboard.setOpaque(true);
        System.out.println(this.btnDashboard.isOpaque());
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        this.btnDashboard.setBackground(new Color(0,0,0,0));
        this.btnDashboard.setOpaque(false);
        System.out.println(this.btnDashboard.isOpaque());
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnDashboard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard1MouseEntered

    private void btnDashboard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard1MouseExited

    private void btnDashboard2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard2MouseEntered

    private void btnDashboard2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard2MouseExited

    private void btnDashboard3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard3MouseEntered

    private void btnDashboard3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard3MouseExited

    private void btnDashboard4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard4MouseEntered

    private void btnDashboard4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard4MouseExited

    private void btnDashboard5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard5MouseEntered

    private void btnDashboard5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard5MouseExited

    private void btnDashboard6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard6MouseEntered

    private void btnDashboard6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard6MouseExited

    private void btnDashboard7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard7MouseEntered

    private void btnDashboard7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardBck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardBck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardBck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardBck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardBck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnDashboard1;
    private javax.swing.JLabel btnDashboard2;
    private javax.swing.JLabel btnDashboard3;
    private javax.swing.JLabel btnDashboard4;
    private javax.swing.JLabel btnDashboard5;
    private javax.swing.JLabel btnDashboard6;
    private javax.swing.JLabel btnDashboard7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
